name: build
on: 
  push: 
    branches: master
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      - uses: rlespinasse/github-slug-action@v2.x
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: tignear
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: guildutils/jumanpp:latest
          cache-from: guildutils/jumanpp:latest
          cache-to: type=inline
